fix: correções visuais contetSwicher
FRST-Falconi/storybook.frstfalconi.com pull request #92
Opened 2022-09-16 18:20 UTC by SuzannePS

## Description

Correções Visuais 

- [#2ytj7z6](https://app.clickup.com/t/2ytj7z6)

## Related Issue
 - N/A
 
## How Has This Been Tested?

![image](https://user-images.githubusercontent.com/93949658/190706060-52b4812e-7d9e-4a48-90b9-c9fab1e8dafd.png)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-16 19:27 UTC, PedroAlvesM requested changes

2022-09-16 19:27 UTC, PedroAlvesM commented on src/components/LXP/contentSwitcher/index.tsx
> +import * as Icons from '../../../shared/icons'
Aqui, seria interessante utlizar esse @shared/icons. Dessa forma, voce não precisa olhar o caminho relativo, e da para improtar em qualquer arquivo. Teve algum problema para carregar os icones?

2022-09-16 20:03 UTC, SuzannePS commented on src/components/LXP/contentSwitcher/index.tsx
> +import * as Icons from '../../../shared/icons'
Atualizado os imports da maneira correta conforme sinalizado

2022-09-16 20:13 UTC, PedroAlvesM reviewed
Ok

2022-09-16 20:13 UTC, PedroAlvesM approved these changes
OK

2022-09-16 21:46 UTC, Marlonps94 commented on src/components/LXP/contentSwitcher/index.tsx
> +                    <Styles.ContentSwitcherSelected sizeIcon={sizeIcon}>
Aqui você está reutilizando o icone Noun e não o startIcon que você recebe como props.

2022-09-20 18:07 UTC, Marlonps94 approved these changes

2022-09-20 18:07 UTC, Marlonps94 commented on src/components/LXP/contentSwitcher/index.tsx
> +                        <Icons.Noun fill={'#ffffff'} />
Aqui você está reutilizando o icone Noun e não o startIcon que você recebe como props.

2022-09-20 18:08 UTC, merged